// render-skills.js — Skills rendering functions extracted from dashboard.html

let _skillsTab = 'all';
let _skillsPage = 0;
const SKILLS_PER_PAGE = 5;

function renderSkills(skills) {
  const el = document.getElementById('skills-list');
  const countEl = document.getElementById('skills-count');
  countEl.textContent = skills.length;
  if (!skills.length) {
    el.innerHTML = '<p class="empty">No skills yet. Agents create these when they discover repeatable workflows.</p>';
    return;
  }

  const sourceIcon = (s) => s === 'claude-code' ? '⚡' : s === 'plugin' ? '🔌' : s?.startsWith('project:') ? '📁' : '🔧';
  const sourceLabel = (s) => s === 'plugin' ? 'plugin' : s?.startsWith('project:') ? s.replace('project:', '') : 'global';

  // Group by source
  const groups = {};
  for (const r of skills) {
    const key = r.source === 'plugin' ? 'plugins' : r.source?.startsWith('project:') ? r.source.replace('project:', '') : 'global';
    if (!groups[key]) groups[key] = [];
    groups[key].push(r);
  }
  const groupKeys = Object.keys(groups).sort((a, b) => a === 'global' ? -1 : b === 'global' ? 1 : a.localeCompare(b));

  // Tab bar
  const tabs = [{ key: 'all', label: 'All (' + skills.length + ')' }];
  for (const k of groupKeys) tabs.push({ key: k, label: k + ' (' + groups[k].length + ')' });

  let html = '<div style="display:flex;gap:4px;margin-bottom:8px;flex-wrap:wrap">';
  for (const t of tabs) {
    const active = _skillsTab === t.key;
    html += '<button class="pr-pager-btn" style="font-size:9px;padding:2px 8px;' +
      (active ? 'background:var(--green);color:#fff;border-color:var(--green)' : '') +
      '" onclick="_skillsTab=\'' + escHtml(t.key) + '\';_skillsPage=0;renderSkills(window._lastSkills)">' + escHtml(t.label) + '</button>';
  }
  html += '</div>';

  // Filter by tab
  const filtered = _skillsTab === 'all' ? skills : (groups[_skillsTab] || []);

  // Paginate
  const totalPages = Math.ceil(filtered.length / SKILLS_PER_PAGE);
  if (_skillsPage >= totalPages) _skillsPage = Math.max(0, totalPages - 1);
  const page = filtered.slice(_skillsPage * SKILLS_PER_PAGE, (_skillsPage + 1) * SKILLS_PER_PAGE);

  html += '<div style="display:flex;flex-direction:column;gap:6px">';
  for (const r of page) {
    const autoTag = r.autoGenerated ? '<span style="font-size:8px;background:rgba(63,185,80,0.15);color:var(--green);padding:1px 4px;border-radius:3px;margin-left:4px">auto</span>' : '';
    html += '<div class="inbox-item" onclick="openSkill(\'' + escHtml(r.file) + '\',\'' + escHtml(r.source || 'claude-code') + '\',\'' + escHtml(r.dir || '') + '\')" style="border-left-color:var(--green)">' +
      '<div class="inbox-name"><span style="color:var(--green);font-weight:600">' + sourceIcon(r.source) + ' ' + escHtml(r.name) + '</span>' + autoTag +
        '<span style="font-size:9px;color:var(--muted);margin-left:auto">' + escHtml(sourceLabel(r.source)) + '</span>' +
      '</div>' +
      (r.description ? '<div class="inbox-preview" style="color:var(--text)">' + escHtml(r.description) + '</div>' : '') +
    '</div>';
  }
  html += '</div>';

  // Pagination controls
  if (totalPages > 1) {
    html += '<div style="display:flex;align-items:center;gap:8px;margin-top:6px;justify-content:center">';
    html += '<button class="pr-pager-btn" style="font-size:9px;padding:2px 8px" ' +
      (_skillsPage === 0 ? 'disabled' : '') +
      ' onclick="_skillsPage--;renderSkills(window._lastSkills)">&laquo;</button>';
    html += '<span style="font-size:10px;color:var(--muted)">' + (_skillsPage + 1) + ' / ' + totalPages + '</span>';
    html += '<button class="pr-pager-btn" style="font-size:9px;padding:2px 8px" ' +
      (_skillsPage >= totalPages - 1 ? 'disabled' : '') +
      ' onclick="_skillsPage++;renderSkills(window._lastSkills)">&raquo;</button>';
    html += '</div>';
  }

  el.innerHTML = html;
  window._lastSkills = skills;
}

function openSkill(file, source, dir) {
  fetch('/api/skill?file=' + encodeURIComponent(file) + '&source=' + encodeURIComponent(source || 'claude-code') + (dir ? '&dir=' + encodeURIComponent(dir) : ''))
    .then(r => r.text())
    .then(content => {
      document.getElementById('modal-title').textContent = file;
      document.getElementById('modal-body').textContent = content;
      document.getElementById('modal-body').style.fontFamily = 'Consolas, monospace';
      document.getElementById('modal-body').style.whiteSpace = 'pre-wrap';
      document.getElementById('modal').classList.add('open');
    })
    .catch(() => {});
}
